app.version: @project.version@
app.api.path: /api/v1
#spring.liquibase.enabled: false
#spring.data.rest.default-page-size: 1000
spring.data.rest.basePath: /api/v1
#spring.jackson.default-property-inclusion: non_null
#spring.jpa.properties.javax.persistence.validation.mode: none
# spring.data.rest.defaultMediaType: application/json
spring.liquibase.change-log: classpath:/defaultDatabase-local.xml

# localhost:3000/h2-console or JDBC URL jdbc:h2:mem:testdb
spring.datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password: password
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.h2.console.enabled: true